Signed responses client
mithril-security/blindai pull request #19
Opened 2022-03-16 15:53 UTC by cchudant

Closes #13 

Thanks to @CerineBnsd for the client part!

2022-03-16 17:20 UTC, JoFrost commented
Thanks a lot! Will review asap

2022-03-16 17:21 UTC, JoFrost commented
@CerineBnsd Can you use Black on the python code?

2022-03-18 11:05 UTC, JoFrost reviewed
All good. Maybe the docstring part as I mentioned would need a few tweaks, but all the rest looks good.

2022-03-18 11:05 UTC, JoFrost commented on client/blindai/client.py
> +        with open("execution_proof.json", "w") as proof_file:
Maybe the docstring can be updated a bit here, explaining the kind of data that will be exported.

2022-03-18 12:34 UTC, CerineBnsd commented
> Thanks for formatting the code. Can anyone of you bump the client and version to 0.3.0, and update the gitbook documentation to reflect all those changes?

I'll update the docstrings, the versions, the client CHANGELOG, and interface reference in gitbook. I think it would be better if @Charles updates the parts that are related to the server as he may explain it better (especially the refactor as it isn't added yest as far as I know).Otherwise, I'll try to do it.

2022-03-18 12:58 UTC, JoFrost commented
The refactor has already been documented! What is left to document is the new feature. You can do the client part and @cchudant the server part.

2022-03-18 15:36 UTC, CerineBnsd commented
> The refactor has already been documented! What is left to document is the new feature. You can do the client part and @cchudant the server part.

It's done for the client-side.

2022-03-18 15:39 UTC, JoFrost commented
> > The refactor has already been documented! What is left to document is the new feature. You can do the client part and @cchudant the server part.
> 
> It's done for the client-side.

Thanks! However, as not the whole documentation is ready and the pull request not done, can you push your changes to the doc as a pull request instead? This way we can merge the moment the feature is added for good to the main branch.

2022-03-18 15:44 UTC, CerineBnsd commented
> Thanks! However, as not the whole documentation is ready and the pull request not done, can you push your changes to the doc as a pull request instead? This way we can merge the moment the feature is added for good to the main branch.

That's right, I didn't pay attention. I'll fix it.

2022-03-21 09:28 UTC, cchudant commented
I've seen that the client now returns the output of the inference instead of a response object with an "output" field
Was this intended? @CerineBnsd 

@JoFrost We are currently pushing the signatures in an array, I was thinking about whether this is the best idea
There is currently no good way to get the signature of an individual signed call, maybe we want to return the proof in the response object returned by run_model and send_model. What do you think?

I will update the server side documentation

2022-03-21 09:46 UTC, CerineBnsd commented
@cchudant For instance, the response object contains the signature + the output of the inference. As we're not returning the response containing the signature in upload_model, it's more consistent not to return the signature in run_model as well, and then what's left as information in the response object will be only the output array.

2022-03-21 17:17 UTC, JoFrost commented
> I've seen that the client now returns the output of the inference instead of a response object with an "output" field Was this intended? @CerineBnsd
> 
> @JoFrost We are currently pushing the signatures in an array, I was thinking about whether this is the best idea There is currently no good way to get the signature of an individual signed call, maybe we want to return the proof in the response object returned by run_model and send_model. What do you think?
> 
> I will update the server side documentation

I definitely agree with your suggestion. @clauverjat What do you think?

2022-03-23 13:03 UTC, JoFrost commented
@cchudant Let's apply your suggestion. Anyway we are only supposed to get the signature of the model we request, and not something else.

2022-03-23 15:56 UTC, JoFrost commented
Alright, the protected branch rules works perfectly.

I will do a final review if you are done. We should expect to merge this on Friday if everything works well. Don't forget about the documentation for the server side as well

2022-03-23 17:03 UTC, JoFrost commented
@cchudant The run tests CI failed again. I think the protobuf python files generation is not working anymore, according to the logs.

2022-03-23 17:27 UTC, cchudant commented
how did that pass the CI, what
I'm so confused

2022-03-25 16:25 UTC, JoFrost requested changes
Add the changes in the changelog, and we can merge this.

2022-03-25 16:25 UTC, JoFrost commented on server/CHANGELOG
> +### Added
The addition/changes are missing.

2022-03-27 16:05 UTC, JoFrost commented on server/CHANGELOG
> +### Added
In order to win some times, I did the change myself. We can speak directly about what is coming next on monday.

2022-03-27 16:05 UTC, JoFrost approved these changes

2022-03-27 16:31 UTC, merged