feature for name added
mithril-security/blindai pull request #94
Opened 2022-07-05 08:17 UTC by casssi

## Description

Model is now save with a name or an uuid if there no name set for the model.

The variable added in the communication for that is name model_id.

2022-07-05 09:01 UTC, cchudant commented on server/blindai_sgx/src/model_store.rs
> +    models_by_nmid: HashMap<Option<String>, InferenceModel>,
why would you want an entry for None in the hashmap

HashMap<String, ...> would be much better

2022-07-05 09:01 UTC, cchudant commented on server/blindai_sgx/src/model.rs
> +        model_id: Option<String>,
keep this an option, and generate the uuid here when None

2022-07-05 09:02 UTC, cchudant commented on server/blindai_sgx/src/model.rs
> +        model_id: Option<String>,
same

2022-07-05 09:02 UTC, cchudant commented on server/blindai_sgx/src/model_store.rs
> +    pub fn delete_model(&self, model_nmid: Option<String>) -> Option<InferenceModel> {
this should be String

2022-07-05 09:41 UTC, cchudant requested changes
This is good! just a little comment

2022-08-02 10:05 UTC, JoFrost commented
Closing as part of the input-output-rework branch.

2022-08-02 10:05 UTC, closed without merging